name: ocr-my-mess
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - pip
  - ocrmypdf
  - pillow
  - tqdm
  - rich
  - typer
  - pyinstaller
  - pytest
  - pymupdf
  # libreoffice is not a standard conda package, it should be installed separately
  - pip:
    - typer[all]
    - ttkbootstrap>=1.10.1
